### ISSUE TITLE
Create different sessions for different user role. For example: admin and user.

### ISSUE THREAD

**Issue by Nasaakaa** [rails/activerecord-session_store#137]
How to create different sessions for using different user. For example.

I redirect to admin login page and session in my cookie is different from user login page. How can i create separate sessions.

**Comment by sikachu** [comment]
Sorry for late reply. This question is actually more fitting for StackOverflow or rubyonrails-talk instead of here, as we reserve the issues to be for reporting problem with the gem only.

For AR::SessionStore, I don't think we have support for multiple session key. However, with one session, you can definitely store the id in different session key (for example, authenticated user could be stored in `user_id` and authenticated admin can be stored in `admin_user_id`). Your authentication gem of choice should support something like this.
