### ISSUE TITLE
get_session is not thread-safe

### ISSUE THREAD

**Issue by emou** [rails/activerecord-session_store#19]
This code is not thread-safe:

      def get_session(env, sid)
          ActiveRecord::Base.logger.quietly do

because ActiveRecord::Base.logger.quietly is not thread-safe.

See https://github.com/rails/rails/issues/11954

The resulting issue is that this can break stdout in a multi-threaded process.

The real-world issue we're hitting is that after upgrading to rails 4, when we run our specs the standard output from rspec disappears, and the test results are not visible.

This happens when there are multiple requests hitting rack, which spawns a thread for each one. These threads in turn call 'get_session' concurrently, and the stdout is being improperly "restored" to '/dev/null' due to the thread unsafety here.

Not sure if this should be fixed here or possibly in active_support (again, https://github.com/rails/rails/issues/11954).

**Comment by sikachu** [comment]
I've implemented the fix for both thread safety issue and `quietly` deprecation and pushed out a prelease gem. Would you mind testing out `0.1.1.pre` and report back if you still run into any issue?

Thanks!

**Comment by sikachu** [comment]
I'm going to release 0.1.1 which should contain the fix. If this is still an issue, please let me know so I will reopen the issue. Thank you for your patience.

**Comment by alexandermalfait** [comment]
Thanks for the fix! This issue was completely crashing my JRuby application. 
All requests would fail with this stack trace:

<pre>
Errno::EBADF (Bad file descriptor - Bad file descriptor):
  org/jruby/RubyIO.java:2097:in `close'
  activesupport (4.1.4) lib/active_support/core_ext/kernel/reporting.rb:51:in `silence_stream'
  activesupport (4.1.4) lib/active_support/core_ext/kernel/reporting.rb:104:in `quietly'
  activerecord-session_store (0.1.0) lib/action_dispatch/session/active_record_store.rb:77:in `set_session'
  rack (1.5.2) lib/rack/session/abstract/id.rb:342:in `commit_session'
  rack (1.5.2) lib/rack/session/abstract/id.rb:226:in `context'
  rack (1.5.2) lib/rack/session/abstract/id.rb:220:in `call'
</pre>

Updating activerecord-session_store to ~> 0.1.1 fixes the issue.
